return {}

-- return {
-- 	"rcarriga/nvim-dap-ui",
-- 	dependencies = { "nvim-neotest/nvim-nio" },
--   -- stylua: ignore
--   keys = {
--     { "<leader>du", function() require("dapui").toggle({ }) end, desc = "Dap UI" },
--     { "<leader>de", function() require("dapui").eval() end, desc = "Eval", mode = {"n", "v"} },
--   },
-- 	opts = {},
-- 	config = function(_, opts)
-- 		local dap = require("dap")
-- 		local dapui = require("dapui")
--
-- 		-- Append your additional configuration here
-- 		opts = vim.tbl_deep_extend("force", opts, {
-- 			-- Your additional configuration
-- 			layouts = {
-- 				{
-- 					elements = {
-- 						{
-- 							id = "scopes",
-- 							size = 0.25,
-- 						},
-- 						{
-- 							id = "breakpoints",
-- 							size = 0.25,
-- 						},
-- 						{
-- 							id = "stacks",
-- 							size = 0.25,
-- 						},
-- 						{
-- 							id = "watches",
-- 							size = 0.25,
-- 						},
-- 					},
-- 					position = "left",
-- 					size = 40,
-- 				},
-- 				{
-- 					elements = {
-- 						{
-- 							id = "repl",
-- 							size = 0.5,
-- 						},
-- 						{
-- 							id = "console",
-- 							size = 0.7,
-- 						},
-- 					},
-- 					position = "bottom",
-- 					size = 10,
-- 				},
-- 			},
-- 			-- Add any other configuration options you want
-- 		})
--
-- 		dapui.setup(opts)
-- 		dap.listeners.after.event_initialized["dapui_config"] = function()
-- 			dapui.open({})
-- 		end
-- 		dap.listeners.before.event_terminated["dapui_config"] = function()
-- 			dapui.close({})
-- 		end
-- 		dap.listeners.before.event_exited["dapui_config"] = function()
-- 			dapui.close({})
-- 		end
-- 	end,
-- }
