return {}

-- return {
--   {
--     "stevearc/conform.nvim",
--     optional = true,
--     opts = {
--       formatters_by_ft = {
--         php = { { "pint", "php_cs_fixer" } },
--         blade = { "blade-formatter" },
--       },
--     },
--   },
--   {
--     -- remove phpcs linter
--     "mfussenegger/nvim-lint",
--     optional = true,
--     opts = {
--       linters_by_ft = {
--         php = {},
--       },
--     },
--   },
--   {
--     "nvim-neotest/neotest",
--     dependencies = {
--       "nvim-lua/plenary.nvim",
--       "nvim-treesitter/nvim-treesitter",
--       "antoinemadec/FixCursorHold.nvim",
--       "olimorris/neotest-phpunit", -- Adapter for PHPUnit / Pest
--     },
--     config = function()
--       local neotest = require("neotest")
--       neotest.setup({
--         adapters = {
--           require("neotest-phpunit")({
--             phpunit_cmd = "vendor/bin/pest",
--             cwd = vim.fn.getcwd(),
--             test_file_pattern = "tests/.*Test.php",
--             filter_dirs = { "vendor" },
--           }),
--         },
--         quickfix = {
--           enabled = true,
--           open = false,
--         },
--       })
--     end,
--   },
--   {
--     -- Add a Treesitter parser for Laravel Blade to provide Blade syntax highlighting.
--     "nvim-treesitter/nvim-treesitter",
--     opts = function(_, opts)
--       vim.list_extend(opts.ensure_installed, {
--         "blade",
--         "php_only",
--       })
--     end,
--     config = function(_, opts)
--       vim.filetype.add({
--         pattern = {
--           [".*%.blade%.php"] = "blade",
--         },
--       })
--
--       require("nvim-treesitter.configs").setup(opts)
--       local parser_config = require("nvim-treesitter.parsers").get_parser_configs()
--       parser_config.blade = {
--         install_info = {
--           url = "https://github.com/EmranMR/tree-sitter-blade",
--           files = { "src/parser.c" },
--           branch = "main",
--         },
--         filetype = "blade",
--       }
--     end,
--   },
--   {
--     -- Add the Laravel.nvim plugin which gives the ability to run Artisan commands
--     -- from Neovim.
--     "adalessa/laravel.nvim",
--     dependencies = {
--       "nvim-telescope/telescope.nvim",
--       "tpope/vim-dotenv",
--       "MunifTanjim/nui.nvim",
--       "stevearc/conform.nvim",
--     },
--     cmd = { "Sail", "Artisan", "Composer", "Npm", "Yarn", "Laravel" },
--     keys = {
--       { "<leader>la", ":Laravel artisan<cr>" },
--       { "<leader>lr", ":Laravel routes<cr>" },
--       { "<leader>lm", ":Laravel related<cr>" },
--     },
--     event = { "VeryLazy" },
--     config = true,
--     opts = {
--       lsp_server = "intelephense",
--       features = { null_ls = { enable = false } },
--     },
--   },
--   {
--     -- Add the blade-nav.nvim plugin which provides Goto File capabilities
--     -- for Blade files.
--     "ricardoramirezr/blade-nav.nvim",
--     dependencies = {
--       "hrsh7th/nvim-cmp",
--     },
--     ft = { "blade", "php" },
--   },
-- }
